# Generated by Django 5.2.6 on 2025-10-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["-order__created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("debit", "Debit Card"),
                    ("wallet", "Digital Wallet"),
                    ("cod", "Cash On Delivery"),
                ],
                default="debit",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
