# Generated by Django 5.2.6 on 2025-10-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders",
         "0003_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
