# Generated by Django 5.2.6 on 2025-10-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(default="item", max_length=20),
        ),
    ]
